import type { PrescriptionUnit } from "@/lib/prescription-knowledge/types";

/**
 * 『メラトニンヨガ™指導者養成講座テキスト』および
 * 『メラトニンヨガ™統合テキスト』からの処方ユニット。
 * Ver.1 は A のみ自動選択。B や独自シグナルでは選ばない。
 */
export const MELATONIN_YOGA_UNITS: readonly PrescriptionUnit[] = [
  {
    id: "my-todays-duration-thinking",
    source: "melatonin_yoga",
    kind: "rest",
    autoSelectable: true,
    slot: "todays_one",
    themes: ["sleep_duration"],
    title: "休息する力",
    reason:
      "公式テキストは、現代人が失っているのは睡眠時間ではなく「休息する力」だと示しています。長く寝るほど良いわけではありません。",
    body: "睡眠時間の長さだけを追わず、いつ眠るか・いつ起きるかも含めて、休息へ還ることを優先してください。長いヨガで夜の睡眠を削らないでください。",
  },
  {
    id: "my-todays-breath-switch",
    source: "melatonin_yoga",
    kind: "breathing",
    autoSelectable: true,
    slot: "todays_one",
    themes: ["sleep_onset"],
    title: "呼吸",
    reason:
      "公式テキストは、夕方から夜へ活動から休息へ切り替えるときに、呼吸を入口にすることを示しています。",
    body: "深く吸うことより、自然に長く吐ける呼吸を数回行ってください。無理に吐かず、吐き終わりを待ちます。",
  },
  {
    id: "my-todays-breath-recovery",
    source: "melatonin_yoga",
    kind: "breathing",
    autoSelectable: true,
    slot: "todays_one",
    themes: ["recovery"],
    title: "呼吸",
    reason:
      "公式テキストは、休めない状態では無理に眠ろうとせず、身体と呼吸から安心を思い出させることを入口にします。",
    body: "緊張すると呼吸は浅く速くなります。数回、ゆっくり長く吐く呼吸から始めてください。入口は常に身体と呼吸です。",
  },
  {
    id: "my-breath-exhale",
    source: "melatonin_yoga",
    kind: "breathing",
    autoSelectable: true,
    slot: "breathing",
    themes: ["sleep_onset", "recovery"],
    title: "長く吐ける呼吸",
    body: "メラトニンヨガ™では、深く吸うことよりも、自然に長く吐ける呼吸を大切にします。吐く息が長くなることで、身体は休息へ向かいやすくなります。無理に吐かず、吐き終わりを待ってください。",
  },
  {
    id: "my-yoga-short",
    source: "melatonin_yoga",
    kind: "yoga",
    autoSelectable: true,
    slot: "yoga",
    themes: ["sleep_onset", "recovery"],
    title: "短いメラトニンヨガ™",
    body: "柔軟性や難しいポーズは目的ではありません。ゆっくり動き、呼吸と動きを合わせ、余計な力を手放す短い実践から始めてください。",
  },
  {
    id: "my-life-bath",
    source: "melatonin_yoga",
    kind: "lifestyle",
    autoSelectable: true,
    slot: "bathing",
    themes: ["sleep_onset"],
    title: "入浴で休息へ切り替える",
    body: "就寝の90〜120分前に、40℃前後のお湯へ10〜15分程度浸かることが一つの目安です。入浴は洗うためだけではなく、休息へ切り替える儀式です。熱すぎるお湯は交感神経を高めるため、就寝前には適しません。",
  },
  {
    id: "my-life-light",
    source: "melatonin_yoga",
    kind: "lifestyle",
    autoSelectable: true,
    slot: "night",
    themes: ["sleep_onset"],
    title: "夜の光と睡眠環境",
    body: "就寝前は間接照明へ切り替え、寝室はできるだけ暗くします。夜の光はメラトニンの分泌を大きく左右します。画面を見る場合も、明るさを下げてください。",
  },
  {
    id: "my-life-nap",
    source: "melatonin_yoga",
    kind: "lifestyle",
    autoSelectable: true,
    slot: "nap_note",
    themes: ["sleep_duration"],
    title: "昼寝をとる場合の目安",
    body: "昼寝をとる場合は、15時までに20分程度にとどめます。長すぎる昼寝は睡眠圧を抜いてしまい、夜の入眠を妨げます。夜の睡眠を削るための昼寝にはしません。",
  },
  {
    id: "my-life-morning",
    source: "melatonin_yoga",
    kind: "lifestyle",
    autoSelectable: false,
    slot: "todays_one",
    themes: [],
    title: "朝から眠りを整える",
    body: "良い眠りは朝から始まります。毎日ほぼ同じ時刻に起き（休日のずれは1〜2時間以内）、起床後1時間以内に屋外の光を15〜30分浴び、身体を軽く動かして呼吸を深め、朝食を摂ることを目安にします。",
  },
  {
    id: "my-life-meal",
    source: "melatonin_yoga",
    kind: "lifestyle",
    autoSelectable: false,
    slot: "todays_one",
    themes: [],
    title: "夕食の時刻",
    body: "夕食は就寝の3時間前までを目安とし、遅くなる場合は量を軽くします。「何を食べるか」だけでなく、「どのように食べるか」も休息を育てる習慣です。",
  },
  {
    id: "my-life-caffeine",
    source: "melatonin_yoga",
    kind: "lifestyle",
    autoSelectable: false,
    slot: "todays_one",
    themes: [],
    title: "カフェインの区切り",
    body: "カフェインは就寝の6時間前までを目安にします。夜まで刺激が続くと、身体は疲れているのに神経だけが興奮したまま夜を迎えやすくなります。",
  },
  {
    id: "my-life-alcohol",
    source: "melatonin_yoga",
    kind: "lifestyle",
    autoSelectable: false,
    slot: "todays_one",
    themes: [],
    title: "アルコールと後半の眠り",
    body: "アルコールは入眠を早めても、睡眠の後半を浅くすることがあります。量と時刻に注意し、夜は調光・入浴・ヨガ・呼吸で休息へ還る流れを優先してください。",
  },
];
